### ISSUE TITLE
Is there a way to create links?

### ISSUE THREAD

**Issue by alandecastros** [salvois/LargeXlsx#16]
Hi,
I've been using your awsome library and I came across a situation that I need to create a link. 
Is there a way?

**Comment by salvois** [comment]
Hi @alandecastros ,
I think we could try to add this functionality.
To my best knowledge, there are many kind of link that can be inserted into an Excel sheet. What is your use case?
Thanks,
   Salvo

**Comment by alandecastros** [comment]
Hi @salvois, 
I need a link to a url.
Thank you

**Comment by AntonyCorbett** [comment]
@alandecastros Just use the "HYPERLINK" function

**Comment by salvois** [comment]
Hi @alandecastros ,
as @AntonyCorbett suggested (thanks!) you may just use the HYPERLINK function with WriteFormula. The alternative method would require writing a new section in the XLSX file, which would require accumulating all hyperlinks in RAM, which is not desirable with this library.
I have added instruction in the documentation and enriched the Simple example to demonstrate that.
Please note that a bug is present in LargeXlsx up to 1.6.1 included, which discards the underline styles when using XlsxFont.With and WithUnderline is not the last one. This is fixed on master.
I'm closing this issue as resolved, please feel free to reopen if you need more.
Thanks,
   Salvo
