### ISSUE TITLE
Feature Request: Writing boolean values

### ISSUE THREAD

**Issue by jim108dev** [salvois/LargeXlsx#18]
Thank you for providing this library. I am using it with F#. It works great and dealing with large files was really painful before.

Would it be possible to implement a `XlsxWriter.Write(bool)` method?

Thanks

**Comment by salvois** [comment]
Hi @jim108dev , it should be pretty easy to do, let me have a look into it.
Thanks,
   Salvo

**Comment by salvois** [comment]
Hi @jim108dev , the requested change has been released in version 1.7.0.
