### ISSUE TITLE
Q&A : DateTime format column

### ISSUE THREAD

**Issue by httt-dev** [salvois/LargeXlsx#27]
I want to use LargeXlsx 1.7.3 to write large data.
I also want format datetime column look like "yyyy/MM/dd HH:mm:ss" , how to format it ?
Thanks

**Comment by dgosbell** [comment]
You can do this by passing a style with a custom format to the overload of the Write method
`xlsxWriter.Write( dt , XlsxStyle.Default.With(new XlsxNumberFormat("yyyy/mm/dd\ hh:mm:ss")));`

**Comment by salvois** [comment]
Hello @httt-dev ,
as @dgosbell said (thanks!), you just need to create, even on the fly, your own style with the very same number format you would write in Excel to format your date.
Thanks,
   Salvo

**Comment by httt-dev** [comment]
Thanks you very much @dgosbell  @salvois
