### ISSUE TITLE
Writing multi line cell content

### ISSUE THREAD

**Issue by abrari-ipb** [salvois/LargeXlsx#29]
Hi, thanks for the great library.

How to properly write a cell with multi-line string content? I have tried using `\n` and `\r\n` in the string, but when opened in Excel, it is shown as single line cell (without the `\n` or `\r\n`). The weird part is, the cell become multi-line only after I double-clicked (or editing) that cell in Excel.

**Comment by salvois** [comment]
Hi @abrari-ipb , this is something I have not tried yet, but I guess you may need rich text content to insert line breaks. My library currently supports only plain text. I'll double check and let you know.
Thanks,
   Salvo

**Comment by abrari-ipb** [comment]
Thanks for your response. After fiddling around, I found that setting alignment with `wrapText: true` make line break works in Excel. 

```cs
var wrapTextStyle = XlsxStyle.Default.With(new XlsxAlignment(wrapText: true));
var content = "multi\nline\nstring";
xlsxWriter.Write(content, wrapTextStyle);
```
