### ISSUE TITLE
Automatic column width adjustment

### ISSUE THREAD

**Issue by anton-voroshilin** [salvois/LargeXlsx#39]
Hi! Are there any plans regarding the implementation of an automatic column width adjustment?
I'm talking about something similar to `AutoFitColumns` in [EPPlus](https://github.com/EPPlusSoftware/EPPlus/wiki/Autofit-columns).
I understand that the way this package is designed requires user to manually provide column width in `BeginWorksheet` method call. However, described feature seems rather handy. 
If, by any chance, you have an idea how to implement it, it would be really great.

**Comment by salvois** [comment]
Hello @anton-voroshilin ,
it is unfortunately not possible to adjust column width while streaming content into the XLSX file being written. The file format specifies that column width must be provided before writing rows, but, unless you keep all your data in memory (which is what LargeXlsx strives to avoid) you can't know the optimal width in advance.
The best you can do is estimate an optimal width in advance, or provide a reasonable value, and specify it in BeginWorksheet as you already noted.
Thanks,
   Salvo

**Comment by anton-voroshilin** [comment]
Thanks for your reply, Salvo!

**Comment by howardhee** [comment]
Hi @salvois , how about allow wrap text for the content since unable adjust the column width? Do we have the feature?

**Comment by salvois** [comment]
Hi @howardhee ,
yes, you can set the word wrap flag in the font alignment style as per documentation.
