### ISSUE TITLE
Generate Excel Worksheet from HTML

### ISSUE THREAD

**Issue by ktb-dev** [salvois/LargeXlsx#47]
Hi!

It would be convenient if it was possible to convert HTML to EXCEL.
The first priority is to add import of HTML tables with support for embedded styles, and in the future it is possible to add support for style sheets as well. 

I think it would be a very useful feature to have.
What do you think about it?  Will you consider this idea in the near future? 

Thanks.

**Comment by salvois** [comment]
Hi @ktb-dev ,
thanks for your suggestion.
Unfortunately I think this is out of the scope of LargeXlsx: this library aims to provide a simple way to write Excel files in a memory-efficient way, but has no feature to read and parse any file format.
   Salvo
