### ISSUE TITLE
MemoryStream supported?

### ISSUE THREAD

**Issue by andreiTeodorescu97** [salvois/LargeXlsx#48]
Is the FileStream a constraint to use XlsxWriter? Is a MemoryStream supported to generate an xlsx file?

**Comment by dgosbell** [comment]
The constructor for XlsxWriter takes an abstract Stream (see https://github.com/salvois/LargeXlsx/blob/7443a933c0e0052da668c2f8de8ee148fa957047/src/LargeXlsx/XlsxWriter.cs#L59) and MemoryStream is a subclass of Stream just like FileStream is so it should work fine.

**Comment by salvois** [comment]
Hi @andreiTeodorescu97 ,
following up @dgosbell  comment (thanks!), you an use any Stream implementation, including MemoryStream.
In fact, you can find it used in this very repository, in the unit tests.
Thanks,
   Salvo
