### ISSUE TITLE
Writing columns after data and comments

### ISSUE THREAD

**Issue by AlleSchonWeg** [salvois/LargeXlsx#52]
Hi,
i'm evaluating some libs to create excel spreadsheets. I have to two questions:
- Is it possible to add comments to cells?
- Can i set the columns (x:cols) after the data rows. Because i need to measure the strings in a column and set the width to the largest value?

Thank you!

**Comment by salvois** [comment]
Hi @AlleSchonWeg ,

> Is it possible to add comments to cells?

This feature is currently not available.

> Can i set the columns (x:cols) after the data rows. Because i need to measure the strings in a column and set the width to the largest value?

This is unfortunately not possible: see https://github.com/salvois/LargeXlsx/tree/1.10.0?tab=readme-ov-file#column-formatting
Your best bet is estimating your column with for an average use case, or, if you can afford it, enumerate your dataset twice.

Thanks,
   Salvo
