### ISSUE TITLE
`xlsxWriter.Write` overwrites `XlsxColumn.Formatted` with DefaultStyle

### ISSUE THREAD

**Issue by PROxZIMA** [salvois/LargeXlsx#54]
Minimal Working Example:

```cs
using System;
using System.Drawing;
using System.IO;
using LargeXlsx;

namespace Examples;

public static class ColumnFormatting
{
    public static void Run()
    {
        var rnd = new Random();
        using var stream = new FileStream($"{nameof(ColumnFormatting)}.xlsx", FileMode.Create, FileAccess.Write);
        using var xlsxWriter = new XlsxWriter(stream);
        var blueStyle = new XlsxStyle(XlsxFont.Default.With(Color.White), new XlsxFill(Color.FromArgb(0, 0x45, 0x86)), XlsxBorder.None, XlsxNumberFormat.General, XlsxAlignment.Default);

        xlsxWriter
            .BeginWorksheet("Sheet 1", columns: new[]
            {
                XlsxColumn.Formatted(count: 2, width: 20),
                XlsxColumn.Unformatted(3),
                XlsxColumn.Formatted(style: blueStyle, width: 9),
                XlsxColumn.Formatted(hidden: true, width: 0)
            });
        for (var i = 0; i < 10; i++)
        {
            xlsxWriter.BeginRow();
            for (var j = 0; j < 10; j++)
                xlsxWriter.Write(rnd.Next());
        }
    }
}
```

Output:

Blue style for column `F` starts after the last row.

![image](https://github.com/user-attachments/assets/1b0d5ea7-7cd7-4638-8642-384d352d1e55)

Expected:

Blue style for column `F` should starts from first row.

![image](https://github.com/user-attachments/assets/d7b353a4-b177-4ff9-b987-969d0069dd11)

> [!NOTE]
> The [column-formatting docs](https://github.com/salvois/LargeXlsx/tree/1.10.0?tab=readme-ov-file#column-formatting) clearly says
> > The column style represents how to style all empty cells of a column. Cells that are explicitly written always use the cell style instead
>
> If the expected result can be achieved via any other flow, please do suggest!!

**Comment by salvois** [comment]
Hi @PROxZIMA ,
I'm afraid this is by design: ["col (Column Width & Formatting) [...] style (Style): Default style for the affected column(s). Affects cells not yet allocated in the column(s)."](https://learn.microsoft.com/en-us/dotnet/api/documentformat.openxml.spreadsheet.column?view=openxml-3.0.1) 
In my understanding, referring you your example, you should specify blueStyle also when you Write() when i == 5. I see it's somewhat redundant but this is the way it works, unfortunately.
Hope this helps,
   Salvo

**Comment by PROxZIMA** [comment]
Ahh, no worries. If aligning to the OpenXML spec is what was intended then it's good to have it like that.

I'll close the issue.

Thanks,
Pratik
