### ISSUE TITLE
Anyway to autosize columns?

### ISSUE THREAD

**Issue by ronnyek** [salvois/LargeXlsx#55]
I generate xlsx files, and all works well, but by default columns are minimal width, and I don't have anyway to know what is ideal length.

I'm wondering if there is anyway I can automatically size them based on the text content within?

**Comment by vitaliy-nerdysoft** [comment]
@ronnyek, That`s the only reason I need a library for Excel native file generation. Have you found a solution for that?

**Comment by dgosbell** [comment]
In this library you need to specify the column widths when creating the worksheet see https://github.com/salvois/LargeXlsx?tab=readme-ov-file#column-formatting so to set the size based on the content you would need to loop through your data and calculate the string width based off the formatting using a technique like one of the ones suggested here https://stackoverflow.com/questions/263614/calculate-the-display-width-of-a-string-in-c to find the maximum size. There is no magic autosize setting.

**Comment by salvois** [comment]
Thanks everyone. This question keeps popping up so it definitely deserves attention, maybe adding a FAQ or a note in the documentation.
By the way, there is a bestFit attribute on the column element that would serve as a hint for spreadsheet applications to enlarge columns automatically when content is input, but last time I checked it didn't work as requested by @ronnyek . I feel like it's worth double checking though. Will let you know.

**Comment by salvois** [comment]
I updated the documentation under https://github.com/salvois/LargeXlsx?tab=readme-ov-file#auto-fit-column-width
