### ISSUE TITLE
Protection of sheets

### ISSUE THREAD

**Issue by MichaCo** [salvois/LargeXlsx#7]
Hi @salvois,
thanks for the great library, its actually working really great in some of my testing.

I know this library will not have all the features in favor of performance and I'm happy about that ^^
The main feature I'm missing right now would be protecting an excel sheet with a password. Do you know if that would be possible somehow?

Thanks
Michael

**Comment by salvois** [comment]
Hi @MichaCo , let's give it a try, I'll let you know!
Thanks,
   Salvo

**Comment by salvois** [comment]
Hi @MichaCo ,
when you talk about password protection, do you mean encrypting the whole file (the "Encrypt with password" option in Excel) or protecting against accidental modification, but keeping the file content human readable (the "Protect current sheet" option in Excel)?
I may have capacity for the latter, but not for the former, unfortunately.
Thanks,
   Salvo

**Comment by MichaCo** [comment]
Yes, just the latter one 🙂
I just need to prevent users from changing data one one sheet for example.

**Comment by salvois** [comment]
Great, let me study how can I add the protection stuff to the worksheet XML and I'll be back to you!
Please allow me some days (I have to do that in the spare time). Thanks!

**Comment by salvois** [comment]
Hi @MichaCo ,
password protection of worksheets is available in LargeXlsx 1.5. The package is being validated by Nuget.org.
Hope this helps!
   Salvo

**Comment by MichaCo** [comment]
Nice job, thanks a lot mate!
